name: バグとクラッシュの報告
description: バグとクラッシュの報告（**VencordJPの開発者のみが使用してください**)
labels: [bug]
title: "[バグ] <title>"

body:
  - type: markdown
    attributes:
      value: |
        ## 必ず読んでください
        翻訳に関する問題はここに出さないでください。(代わりに翻訳の問題テンプレートを使用してください)
        この報告は、VencordJPの関係者のみが使用できます。それ以外の方はDiscordでご連絡ください。
  
  - type: input
    id: discord
    attributes:
      label: Discordのアカウント
      description: あなたのDiscordアカウントのIDをここに入力してください。
      placeholder: username#0000, username
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: どこにバグがありますか？
      description: ○○をするとクラッシュ/バグが発生するクラッシュやバグはVencordのオリジナルの問題である可能性があります。オリジナルのVencordも試してください。
      placeholder: ○○が動いていません、○○をするとクラッシュします、etc..
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: それはどこで発生していますか？
      description: この問題が起きる場所を記載してください。
      placeholder: 設定、プラグイン、etc..
    validations:
      required: true

  - type: textarea
    id: steps-to-take
    attributes:
      label: このバグはどの手順で発生しますか？
      description: このバグが発生する手順を記載してください。
      placeholder: |
        1. ○○を開きます
        2. ○○をします
        3. ○○をして、○○をすると
        4. バグ/クラッシュが発生します
    validations:
      required: true

  - type: textarea
    id: crash-log
    attributes:
      label: エラー
      description: Ctrl+Shift+Iを押して開発者ツールを開き、コンソールタブにある赤い文字（failed to load resource等のエラーは無視で）をコピーして"```"で囲んで貼り付けてください。
      value: |
        ```
        エラーログはここに貼り付けてください...
        ```
    validations:
      required: false

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: We only accept reports for bugs that happen on Discord Stable. Canary and PTB are Development branches and may be unstable
      options:
        - label: I am using Discord Stable or tried on Stable and this bug happens there as well
          required: true
        - label: I have read the requirements for opening an issue above
          required: true
